# -*- coding: utf-8 -*-
"""task1_128_first version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_mAFSv8zm8ZZMSFn2eZ5MN7ZMDOicSgh

<div class="alert alert-block alert-success">
    
# FIT5196 Task 1 in Assessment 1
#### Student Name: xxxx
#### Student ID: xxxx

Date: xxxx


Environment: Python xxxx

Libraries used:
* re (for regular expression, installed and imported)
* pandas (for data manipulation)
    
</div>

<div class="alert alert-block alert-danger">
    
## Table of Contents

</div>    

[1. Introduction](#Intro) <br>
[2. Importing Libraries](#libs) <br>
[3. Examining Patent Files](#examine) <br>
[4. Loading and Parsing Files](#load) <br>
$\;\;\;\;$[4.1. Defining Regular Expressions](#Reg_Exp) <br>
$\;\;\;\;$[4.2. Reading Files](#Read) <br>
$\;\;\;\;$[4.3. Whatever else](#latin) <br>
[5. Writing to CSV/JSON File](#write) <br>
$\;\;\;\;$[5.1. Verification - using the sample files](#test_xml) <br>
[6. Summary](#summary) <br>
[7. References](#Ref) <br>

-------------------------------------

<div class="alert alert-block alert-warning">

## 1.  Introduction  <a class="anchor" name="Intro"></a>
    
</div>

This assessment is about extracting data from semi=structured text files. The datasets which were given to us were around 14 text files as well as 1 excel file where the information about user views.

-------------------------------------

<div class="alert alert-block alert-warning">
    
## 2.  Importing Libraries  <a class="anchor" name="libs"></a>
 </div>

The packages to be used in this assessment are imported in the following. They are used to fulfill the following tasks:

* **re:** to define and use regular expressions
* **pandas:** to be used for data manipulation and analysis
* **json:** used for converting a file into JSON format
* **datatime:** used for allowing for date and time in the given file
"""

# imported regular expression
import re
#imported json
import json
#imported pandas
import pandas as pd
#imported date and time
from datetime import datetime

# to run the google colab
from google.colab import drive
drive.mount('/content/drive')

"""-------------------------------------

<div class="alert alert-block alert-warning">

## 3.  Examining Raw Data <a class="anchor" name="examine"></a>

 </div>

First of all, ....

Having examined the file content, the following observations were made:

-------------------------------------

<div class="alert alert-block alert-warning">

## 4.  Loading and Parsing Files <a class="anchor" name="load"></a>

</div>

In this section, the files are parsed and processed. First of all, appropriate regular expressions are defined to extract desired information when reading the files. ....

-------------------------------------

<div class="alert alert-block alert-info">
    
### 4.1. Defining Regular Expressions <a class="anchor" name="Reg_Exp"></a>

Defining correct regular expressions is crucial in extracting desired information from the text efficiently. ...
"""

pattern_id = r'...' #reg ex pattern for id

"""These patterns are used in the next step when reading the files.

-------------------------------------

<div class="alert alert-block alert-info">
    
### 4.2. Reading Files <a class="anchor" name="Read"></a>

In this step, all files are read and parsed.

Let's take a look at the first ten elements of the lists generated. We can see that ids, reviews,etc. are parsed and stored correctly.

-------------------------------------

<div class="alert alert-block alert-info">
    
### 4.3. Whatever else <a class="anchor" name="latin"></a>

the rest of your methodology

-------------------------------------

<div class="alert alert-block alert-warning">

## 5.  Writing to JSON File <a class="anchor" name="write"></a>

</div>

....

-------------------------------------

<div class="alert alert-block alert-info">
    
### 5.1. Verification of the Generated JSON File <a class="anchor" name="test_xml"></a>

<div class="alert alert-block alert-warning">

## 6. Summary <a class="anchor" name="summary"></a>

</div>

....

-------------------------------------

....

-------------------------------------

<div class="alert alert-block alert-warning">

## 7. References <a class="anchor" name="Ref"></a>

</div>

[1]<a class="anchor" name="ref-2"></a> Why do I need to add DOTALL to python regular expression to match new line in raw string, https://stackoverflow.com/questions/22610247, Accessed 30/08/2022.


[2]<a class="anchor" name="ref-2"></a> W3Schools. (n.d.). Python JSON. W3Schools. Retrieved August 27, 2024, from https://www.w3schools.com/python/python_json.asp

[3] <a class="anchor" name="ref-2"></a> https://colab.research.google.com/drive/15ra-ekowBK0q8Knrx2juCfQRmG-qXZWy?authuser=2 - Applied class 1 - import google colab

....

## --------------------------------------------------------------------------------------------------------------------------
"""